# Set Site Details
site_name: "The DStillery"
site_url: "http://dstillery.com"
version: "v0.1"
require_email_activation: true

file_storage: file

# SEO Stuff
default_meta_keywords: "NintendoDS Nintendo DS Homebrew Games Application"
default_meta_description: "Community driven Nintendo DS homebrew site."

# Paging Sizes
projects_per_page: 6

# Set Avatar Sizes
screenshot_sizes: 
  medium: "256x384"
  thumb: "70x70"

# Set default avatar
screenshot_default: "/images/default_screenshots/:style.png"

spam_question: What is 3 plus 3?
spam_answer: 
  - "6"
  - "six"

show_morph: false

blog_url: "http://weblog.brightlight-ict.nl/category/the_dstillery/"
